// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = const FirebaseOptions(
    apiKey: 'AIzaSyBOqf6lJ5iVqmVL53deVJgT1XEzXsahEwo',
    appId: '1:1006317565593:web:c267cdb67a68e5746aaa08',
    messagingSenderId: '1006317565593',
    projectId: 'fir-cli-a7a20',
    authDomain: 'fir-cli-a7a20.firebaseapp.com',
    storageBucket: 'fir-cli-a7a20.appspot.com',
    measurementId: 'G-NFM8H01637',
  );

  static FirebaseOptions android = const FirebaseOptions(
    apiKey: 'AIzaSyCn_lJrKTFClRsjfiYjvlYrxCjxbSZbYoc',
    appId: '1:1006317565593:android:8e7b181cab74b2856aaa08',
    messagingSenderId: '1006317565593',
    projectId: 'fir-cli-a7a20',
    storageBucket: 'fir-cli-a7a20.appspot.com',
  );
}
